import Head from "next/head";
import { useTheme } from "next-themes";
import { useEffect } from "react";
import HomeEntry from "../components/Home/HomeEntry";

export default function Home() {
  const { theme, setTheme } = useTheme();

  useEffect(() => {
    setTheme("dark");
  }, []);

  const ToggleTheme = () => {
    setTheme(theme === "light" ? "dark" : "light");
  };
  return (
    <div>
      <Head>
        <title>Orpheus Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-black bg-white min-h-screen">
        <HomeEntry />
      </main>
    </div>
  );
}
