import Head from "next/head";
import { useTheme } from "next-themes";
import { useEffect } from "react";
import HomeEntry from "../components/Home/HomeEntry";
import { ThemeContext } from "../contexts/ThemeContext";

export default function Home() {
  const { theme, setTheme } = useTheme();

  useEffect(() => {
    setTheme("dark");
  }, []);

  return (
    <div>
      <Head>
        <title>Orpheus Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeContext.Provider value={{ theme, setTheme }}>
        <main className="dark:bg-black bg-white min-h-screen">
          <HomeEntry />
        </main>
      </ThemeContext.Provider>
    </div>
  );
}
